### PR TITLE
Issue #2715913: Allow for selecting a stock service by entity bundle type

### PR DESCRIPTION
**Pull request by steveoliver**
See https://www.drupal.org/node/2715913

### CODE REVIEW

**Comment by BBGuy** [comment]
Haven't finished going over all of it but looks and behaves as expected. Only comment I have so far is about the removal of the StockServiceManagerConfig calss and interface. 
The idea was to allow the determination of the stock service to to be overridable if needed. Although by PurchasableEntity type is the most logical, but others may have other ways of identifying this like using taxonomy terms. Also always in stock will be needed on a product level but this is probably better handled by adding this functionality to the local stock service. 
I am happy to push as is and we can add an issue for a later date as this is probably a reasonable constraint and we should move on.

**Comment by BBGuy** [comment]
The correlation of the configuration with PurchasableEntity can also allow us to automate the creation of the stock level field at a later stage.

**Comment by steveoliver** [comment]
@BBGuy I understand the intent of the config class, but since it doesn't currently do anything but get config, and we may find another cleaner way of accomplishing the override / configuration on the entity level, I think we can clean things up here (as is) and address this feature in another issue.

**Comment by BBGuy** [comment]
This is now merged and pushed to both github and drupal.org

**Pull request closed without merging**
